### ISSUE TITLE
not working showing 404

### ISSUE THREAD

**Issue by krcpr007** [adi-g15/nitp-notes#2]
error showing

**Comment by adi-g15** [comment]
Thanks bhai :+1:, actually ye 41b0691eb9db4614238afd194005c3a8739fb83e commit ke wajah se hua tha intentionally, since our course was completed.

I am again changing the netlify config to use `main` branch instead, so the website will show correctly. But note that the **links on website are only accessible to students of National Institute of Technology Patna**. It should be working again, if not use `Ctrl`+`F5`.

PS: Agar fix ho jaye to issue close kardena @krcpr007 : )
